name = "Josef 'Josaft' Ibrahim"
description = "Educator, 3D Generalist, and Motion Designer passionate about creativity and innovation."
keywords = "Josef Ibrahim, Josaft, 3D Generalist, Motion Designer, educator, art, portfolio"
image = "josaft.webp"
theme = "dark"
primary_color = "#ff5733"
text_align = "center"
gtag_id = "G-XXXXXXX"
base_url = "https://josaft.at"

[[sections]]
title = "Socials"
description = "Connect with me on my social platforms."
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Instagram"
url = "https://www.instagram.com/josaft"
[[sections.items]]
title = "LinkedIn"
url = "https://www.linkedin.com/in/josaft"
[[sections.items]]
title = "Twitter"
url = "https://twitter.com/josaft"
[[sections.items]]
title = "YouTube"
url = "https://www.youtube.com/josaft"

[[sections]]
title = "Portfolio"
description = "Explore my work on these platforms."
direction = "row"
item_style = "outline"
[[sections.items]]
title = "ArtStation"
url = "https://www.artstation.com/josaft"
[[sections.items]]
title = "Dribbble"
url = "https://dribbble.com/josaft"
[[sections.items]]
title = "Behance"
url = "https://www.behance.net/josaft"
[[sections.items]]
title = "Vimeo"
url = "https://vimeo.com/josaft"

[[sections]]
title = "Website"
description = "Visit my website for more information."
direction = "column"
item_style = "filled"
[[sections.items]]
title = "Josaft"
description = "My personal website featuring my portfolio and contact info."
url = "https://josaft.at"
